baseURL = "https://owaspsamm.org/"
title = "OWASP SAMM"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-127457120-1"

# Define the number of posts per page
paginate = 10

[menu]

# Main menu

[[menu.main]]
    name = "About SAMM"
    url  = "/about/"
    weight = 1

[[menu.main]]
    name = "The model"
    url  = "/model/"
    weight = 2

[[menu.main]]
    name = "Community"
    identifier = "community"
    url  = ""
    weight = 7

[[menu.main]]
    name = "Blog"
    parent = "community"
    url  = "/blog/"
    weight = 3

[[menu.main]]
    name = "Events"
    identifier = "events"
    parent = "community"
    url  = "/events/"
    weight = 4

[[menu.main]]
    name = "Sponsors"
    identifier = "sponsors"
    parent = "community"
    url  = "/sponsors/"
    weight = 5

[[menu.main]]
    name = "Guidance"
    identifier = "guidance"
    url  = ""
    weight = 6

[[menu.main]]
    name = "Getting started"
    parent = "guidance"
    url  = "/guidance/quick-start-guide/"
    weight = 5

[[menu.main]]
    name = "Assessment"
    parent = "guidance"
    url  = "/assessment/"
    weight = 6

[[menu.main]]
    name = "Benchmarking"
    parent = "guidance"
    url  = "/benchmarking/"
    weight = 7

#[[menu.main]]
#    name = "Version 1.5"
#    url  = "/v15/"
#    weight = 6

# [[menu.main]]
#     name = "FAQ"
#     url  = "/faq/"

#     weight = 7

[[menu.main]]
    name = "User Day"
    url  = "/user-day/"
    weight = 8

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 9

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/OWASP/samm"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Slack"
    url = "https://owasp.slack.com/messages/C0VF1EJGH"
    pre = "<i class='fab fa-2x fa-slack'></i>"

[[menu.topbar]]
    weight = 3
    name = "LinkedIn"
    url = "https://www.linkedin.com/company/owasp-samm/"
    pre = "<i class='fab fa-2x fa-linkedin-in'></i>"

[[menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "https://twitter.com/OwaspSAMM"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:info@owaspsamm.org"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"
    
    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "samm"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "info@owaspsamm.org"

    about_us = "<p>This is an OWASP Project.</br>OWASP is an open community dedicated to enabling organizations to conceive, develop, acquire, operate, and maintain applications that can be trusted. All of the OWASP tools, documents, forums, and chapters are free and open to anyone interested in improving application security.</p>"
    about_us_img = "/img/owasp_logo_1c_w_notext.png"
    about_us_url = "https://owasp.org"
    copyright = "OWASP SAMM is published under the"
    copyright_url = "https://creativecommons.org/licenses/by-sa/4.0/"
    copyright_url_text = "CC BY-SA 4.0 license"

    privacy_policy = "and we share the"
    privacy_policy_url = "https://www2.owasp.org/www-policy/operational/privacy"
    privacy_policy_url_text = "OWASP Privacy Policy"
    
    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "/img/logo.png"
    logo_small = "/img/logo-small.png"
    # address = """<p><strong>Universal Ltd.</strong>
    #     <br>13/25 New Avenue
    #     <br>Newtown upon River
    #     <br>45Y 73J
    #     <br>England
    #     <br>
    #     <strong>Great Britain</strong>
    #   </p>
    #   """
    # latitude = "-12.043333"
    # longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fas fa-calendar"
    title = "Do you want to see more?"
    subtitle = "We have prepared a list of upcoming SAMM events and trainings."
    link_url = "/events"
    link_text = "Check SAMM events"

[params.subscribe]
    enable = true
    icon = "far fa-paper-plane"
    title = "Get SAMM news delivered to you"
    subtitle = ""
    link_url = "https://owaspsamm.us9.list-manage.com/subscribe?u=b83ce65c91239cb5e623ea83e&id=cbd0520923"
    link_text = "Subscribe to our newsletter"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Sponsors"
    subtitle = "Software powers the world, but insecure software threatens safety, trust, and economic growth."
    subtitle2 = "Your support powers SAMM and helps us achieve our mission."
    link_url = "/sponsors"
    link_text = "Find out about sponsorship"

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "Be an OWASP SAMM contributor and tell us about your experience using our maturity model in guest articles. Get in touch with us to share your SAMM story."

[markup.goldmark.renderer]
    unsafe = true